### PR TITLE
Tweaked upstream name

### PR DESCRIPTION
**Pull request by 0atman**
FIxed for compatability with older versions of django
# QA

You're not going to QA it

### CODE REVIEW

**Comment by nottrobin** [comment]
LGTM :+1: good find

**Comment by 0atman** [comment]
@nottrobin hey man, would you still like this guy?

**Comment by nottrobin** [comment]
Good point. Yes please. Are you able to merge it?

**Comment by nottrobin** [comment]
oh wait, this is merging into _your_ master. Don't worry, I'll merge it into upstream.

**Comment by nottrobin** [comment]
Actually I think this is taken care of in upstream. Go ahead and delete this.

**Pull request closed without merging**
